import time
time.sleep(1.7)
print ("\n\n     Baby anh muon noi \n")
time.sleep(1.7)
print ("\n     Baby anh muon noiii\n")
time.sleep(2.1)
print("\n     Anh yeu em\n")
time.sleep(1.2)
print("\n     Du bay lau anh chi cat giu o trong tim...\n")
time.sleep(3.1)
print("\n     Chang the noi nen loi\n")
time.sleep(2)
print("\n     Cam xuc kia roi boi.\n")
time.sleep(1.2)
print("     Anh biet!!\n")
